# Your database type
# - IN_MEMORY (default)
# - MYSQL
database-type: IN_MEMORY

# Print all operations inside the database in the console with the value formatted as Json
debug-mode: false

# The number of thread that will be used for your async database call
# If you are using MySQL, I would advice to set the same number as "minimum idle connection"
# In the case were you have more than 3 running operation, extra thread will be created temporarily
idle-thread-pool-size: 3

database:
  mysql:

    # Full host path containing host:port/database_name
    # exemple: jdbc:mysql://localhost:3306/ndatabase
    host: 'jdbc:mysql://localhost:3306/your_database_name'
    user: ''
    pass: ''

    # Depending on your MySQL version or fork, you may want to change the driver
    # default com.mysql.jdbc.Driver
    driver-class-name: 'com.mysql.jdbc.Driver'

    # Set the minimum constantly opened connection with your database
    # note that the number of plugin won't multiply this number
    # so you can config this number according to your needs
    minimum-idle-connection: 3

    # Maximum number of connection in the pool
    maximum-pool-size: 10